import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import React from "react";
import { UserStoreProvider } from "@/providers/user-store-provider";
import { ProductStoreProvider } from "@/providers/product-store-provider";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.className} ${geistMono.className} h-full antialiased`}
    >
      <body className="min-h-full grid grid-rows-[auto_1fr]">
        <UserStoreProvider>
          <ProductStoreProvider>
            {children}
          </ProductStoreProvider>
        </UserStoreProvider>
        <Toaster />
      </body>
    </html>
  );
}
